name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.2.2
issue_tracker: https://github.com/samuel-s-marques/flutter_chatview/issues
repository: https://github.com/samuel-s-marques/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.11
  emoji_picker_flutter: ^1.5.4
  http: ^0.13.6
  html: ^0.15.3
  any_link_preview: ^3.0.0
  progress_indicators: ^1.0.0
  image_picker: ^0.8.7+5
  audio_waveforms: ^1.0.4
  timeago: ^3.4.0
  flutter_parsed_text: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
